version: '3.0'

expectations:
  population_size: 1000

actions:

### Monthly tallies.
  generate_cohorts_long_emis:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_EMISmeasures_bycode --index-date-range "2019-01-01 to 2020-12-01 by month" --output-dir=output/emismeasures
    outputs:
      highly_sensitive:
        cohort: output/emismeasures/input_EMISmeasures_bycode_*.csv

  generate_measures_emis:
    run: cohortextractor:latest generate_measures --study-definition study_definition_EMISmeasures_bycode --output-dir=output/emismeasures
    needs: [generate_cohorts_long_emis]
    outputs:
      moderately_sensitive:
        measure_csv: output/emismeasures/measure_*.csv

  run_model_long_emis:
    run: r:latest analysis/EMIS03-createnattrends_codes.R
    needs: [generate_cohorts_long_emis]
    outputs:
      moderately_sensitive:
        log: logs/log-EMIS03-createnattrends.txt
        tb01: output/tables/sc03_tb01_nattrends.csv
        fig01: output/plots/EMISsc03_fig01_nattrends.svg
        fig02: output/plots/EMISsc03_fig02_nattrends.svg
        fig03: output/plots/EMISsc03_fig03_pracnatcoverage.svg


### Weekly tallies to compare with OC/VC supplier data. https://docs.opensafely.org/en/latest/measures/
  generate_cohorts_weekly2021_emis:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_EMISmeasures_weekly --index-date-range "2020-01-06 to 2021-05-31 by week" --output-dir=output/emismeasures-weekly
    outputs:
      highly_sensitive:
        cohort: output/emismeasures-weekly/input_EMISmeasures_weekly_*.csv

  generate_measures_weekly2021_emis:
    run: cohortextractor:latest generate_measures --study-definition study_definition_EMISmeasures_weekly --output-dir=output/emismeasures-weekly
    needs: [generate_cohorts_weekly2021_emis]
    outputs:
      moderately_sensitive:
        measure_csv: output/emismeasures-weekly/measure_*.csv

  run_model_weekly2021_emis:
    run: r:latest analysis/EMIS04-weekly2021.R
    needs: [generate_cohorts_weekly2021_emis,generate_measures_weekly2021_emis]
    outputs:
      moderately_sensitive:
        log: logs/log-EMIS04-weekly2021.txt
        tab1: output/tables/EMISsc04-weeklynattrend.csv
